version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
  monitor:
    network_mode: bridge
    build:
      dockerfile: ./lan_monitor/Dockerfile
  api:
    build:
      dockerfile: ./web/api/Dockerfile
    environment:
      FLASK_ENV: dev
    command: gunicorn -w 1 -b :5001 app:app
    ports:
      - "5001:5001"




volumes:
  mongo-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "f:/mongo/"