version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - lan-monitor
  monitor:
    network_mode: host
    build:
      context: .
      dockerfile: ./lan_monitor/Dockerfile
    command: python -u lan_monitor/main.py -c ./config.dev.yaml -i 10 -s 2 -d
  api:
    build:
      context: .
      dockerfile: ./web/api/Dockerfile
    environment:
      FLASK_ENV: prod
    command: gunicorn -w 1 -b :5001 app:app
    expose:
      - "5001"
    networks:
      - lan-monitor
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - lan-monitor

volumes:
  mongo-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "f:/mongo/"

networks:
  lan-monitor:
    driver: bridge